# Atividade 6 - Modelo SVM

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [6]:
from sklearn.datasets import load_iris
data = load_iris()
df_iris = pd.DataFrame(data['data'], columns=data.feature_names)
df_iris['target'] = data.target

In [21]:
df_iris.head(80)
#Iris Setosa -->0
#Iris Versicolor --> 1
#Iris Virginica --> 2

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
75       1  
76       1  
77       1  
78       1  
79       1  

[80 rows x 5 columns]

In [8]:
df_iris.describe()


sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [9]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [14]:
X = df_iris.drop('target', axis=1)
y = df_iris['target']


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [16]:
#default
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [17]:
y_pred = model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 15  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.94      0.97        16
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



### Variações -- Adicionais com diferentes KERNEL's

In [22]:
#Kernel: degree(grau) somente para o kernel polinomial 
model_poly = SVC(kernel='poly', degree=8)
model_poly.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [23]:
y_pred_poly = model_poly.predict(X_test)

In [24]:
print(confusion_matrix(y_test, y_pred_poly))
print(classification_report(y_test, y_pred_poly))

[[ 8  0  0]
 [ 0 15  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.94      0.97        16
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



In [27]:
#Kernel: sigmoid
model_sig = SVC(kernel='sigmoid')
model_sig.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [28]:
y_pred_sig = model_sig.predict(X_test)

In [30]:
#Isso ocorre porque a função sigmóide retorna dois valores, 0 e 1, portanto é mais adequada para problemas de classificação binária. No entanto, em nosso caso, tínhamos três classes de saída.
import warnings
warnings.filterwarnings("ignore")
print(confusion_matrix(y_test, y_pred_sig))
print(classification_report(y_test, y_pred_sig))

[[ 0  0  8]
 [ 0  0 16]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.00      0.00      0.00        16
           2       0.20      1.00      0.33         6

    accuracy                           0.20        30
   macro avg       0.07      0.33      0.11        30
weighted avg       0.04      0.20      0.07        30

