# Atividade 2 - análise de dados com Numpy, Pandas e Matplotlib

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

# Numpy
1. Considere o array 1D a declarado abaixo. Printe o shape dele. Transforme ele em um array 3D no seguinte formato e printe o novo shape:
```python
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
```

2. Considere os arrays a1 e a2 declarados abaixo. Crie um array a3 que é o empilhamento horizontal de a1 e a2:
```python
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
```
Crie também o array a4 que é o empilhamento vertical de a1 e a2:
```python
[[ 1,  2,  3],
 [ 4,  5,  6],
 [ 7,  8,  9],
 [10, 11, 12]]
```

3. Crie a transposta de a3 e selecione todos elementos da terceira e quarta coluna.
```python
[[ 3,  7],
 [ 6, 10]]
```
4. Selecione os elementos do array a4 que são divisíveis por 2.
5. Calcule a média de cada coluna do array a4.
6. Considere a matriz $X$ e o vetor $y$, armazenadas nos arquivos X.npy e y.npy respectivamente. Faça a leitura desses arquivos. Calcule o vetor $w$ que é dado por: 
$$
w = (X^\top X)^{-1}X^\top y
$$

Relembrando: $X^\top$ é a transposta de $X$ e $X^{-1}$ é a inversa de $X$. Utilizar a multiplicação de matrizes.


In [3]:
a = np.array([x for x in range(27)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Questão 1 -- Resolução

1. Considere o array 1D a declarado abaixo. Printe o shape dele. Transforme ele em um array 3D no seguinte formato e printe o novo shape:

```python
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
```

In [21]:
#printando o shape
print(a.shape)

(3, 3, 3)


In [9]:
a = a.reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [10]:
print(a.shape)

(3, 3, 3)


# Questão 2 -- Resolução
2. Considere os arrays a1 e a2 declarados abaixo. Crie um array a3 que é o empilhamento horizontal de a1 e a2:
```python
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
```
Crie também o array a4 que é o empilhamento vertical de a1 e a2:
```python
[[ 1,  2,  3],
 [ 4,  5,  6],
 [ 7,  8,  9],
 [10, 11, 12]]
```

In [11]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])


In [13]:
#Empilhamento horizontal
a3 = np.hstack((a1, a2))
print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
#Empilhamento vertical
a4 = np.vstack((a1, a2))
print(a4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Questão 3 -- Resolução 
3. Crie a transposta de a3 e selecione todos elementos da terceira e quarta coluna.
```python
[[ 3,  7],
 [ 6, 10]]
```

In [15]:
a_t = a3.T
print(a_t)

[[ 1  4]
 [ 2  5]
 [ 3  6]
 [ 7 10]
 [ 8 11]
 [ 9 12]]


In [18]:
a_t[2:4]

array([[ 3,  6],
       [ 7, 10]])

# Questão 4 -- Resolução
4. Selecione os elementos do array a4 que são divisíveis por 2.

In [19]:
divisible_by_2 = a4[a4%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


# Questão 5 -- Resolução
5. Calcule a média de cada coluna do array a4.

In [20]:
a4.mean(axis=0)

array([5.5, 6.5, 7.5])

# Questão 6 -- Resolução
6. Considere a matriz $X$ e o vetor $y$, armazenadas nos arquivos X.npy e y.npy respectivamente. Faça a leitura desses arquivos. Calcule o vetor $w$ que é dado por: 
$$
w = (X^\top X)^{-1}X^\top y
$$

Relembrando: $X^\top$ é a transposta de $X$ e $X^{-1}$ é a inversa de $X$. Utilizar a multiplicação de matrizes.

In [37]:
matriz_x = np.load('data/X.npy')
vetor_y = np.load('data/y.npy')
x_t = matriz_x.T
mult = np.linalg.inv(x_t@matriz_x)@x_t
w = mult@vetor_y
#mult_2 = np.linalg.inv(x_t.dot(matriz_x)).dot(x_t) ==== Aparentemente, utilizando .dot, dá o mesmo resultado
#w_2 = mult.dot(vetor_y)
w

array([[ 1.19709032e+03],
       [-1.56045693e+01],
       [ 5.61262883e+01],
       [-3.91995690e+01],
       [ 1.46953329e+02],
       [ 4.35415783e+04]])

# Pandas

Considere o conjunto de dados de gorjetas, onde as variáveis são:
* total_bill = valor total da conta
* tip = valor da gorjeta
* sex = sexo do cliente
* smoker = se o cliente é fumante
* day = dia da semana
* time = qual refeição
* size = tamanho da mesa

A partir desse conjunto de dados responda utilizando as bibliotecas de análise de dados.

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

1. Qual a média, desvio padrão, valores máximos e mínimos de total_bill, tip e size?
1. Qual a quantidade de refeições que ocorreram em cada dia da semana ('day')? E qual a quantidade em cada tipo de refeição ('time')?
1. Crie uma nova coluna chamada percentage que indica a razão entre tip e total_bill. Qual a média, desvio padrão, valores máximos e mínimos dessa nova variável? Retorne a refeição que teve a maior percentage.
1. Qual a média, desvio padrão, valores máximos e mínimos de percentage para clientes do sexo masculino? E para o sexo feminino?
1. Considere os clientes que deram gorjeta cuja porcentagem estava abaixo da média. Quantos são fumantes e quantos são não fumantes?
1. Quais as correlações entre total_bill, tip, size e percentage?
1. Traga alguma informação nova que você julgue interessante sobre esses dados e que ainda não vou abordada nas questões anteriores.

# Questão 1 - Resolução
1. Qual a média, desvio padrão, valores máximos e mínimos de total_bill, tip e size?

In [53]:
df['total_bill'].describe()

count    244.000000
mean      19.785943
std        8.902412
min        3.070000
25%       13.347500
50%       17.795000
75%       24.127500
max       50.810000
Name: total_bill, dtype: float64

In [50]:
df['tip'].describe()

count    244.000000
mean       2.998279
std        1.383638
min        1.000000
25%        2.000000
50%        2.900000
75%        3.562500
max       10.000000
Name: tip, dtype: float64

In [51]:
df['size'].describe()

count    244.000000
mean       2.569672
std        0.951100
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: size, dtype: float64

# Questão 2 -- Resolução
2. Qual a quantidade de refeições que ocorreram em cada dia da semana ('day')? E qual a quantidade em cada tipo de refeição ('time')?

In [7]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [8]:
df['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

# Questão 3 -- Resolução
3. Crie uma nova coluna chamada percentage que indica a razão entre tip e total_bill. Qual a média, desvio padrão, valores máximos e mínimos dessa nova variável? Retorne a refeição que teve a maior percentage.

In [17]:
df['percentage'] = df.apply(lambda x:x['tip']/x['total_bill'],axis=1)
#Convertendo de ponto flutuante para porcentagem
#df['percentage'] = pd.Series(["{0:.2f}%".format(val * 100) for val in df['percentage']], index = df.index)
df

total_bill   tip     sex smoker   day    time  size  percentage
0         16.99  1.01  Female     No   Sun  Dinner     2    0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3    0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3    0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2    0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4    0.146808
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3    0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2    0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2    0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2    0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2    0.159744

[244 rows x 8 columns]

In [44]:
df['percentage'].describe()
#0.710344827586207

count    244.000000
mean       0.160803
std        0.061072
min        0.035638
25%        0.129127
50%        0.154770
75%        0.191475
max        0.710345
Name: percentage, dtype: float64

In [51]:
#Dados da refeição com a maior porcentagem
df.loc[df['percentage']==0.710344827586207]

total_bill   tip   sex smoker  day    time  size  percentage
172        7.25  5.15  Male    Yes  Sun  Dinner     2    0.710345

# Questão 4 -- Resolução
4. Qual a média, desvio padrão, valores máximos e mínimos de percentage para clientes do sexo masculino? E para o sexo feminino?

# Matplotlib e Seaborn
Ainda sobre o dataset da questão anterior crie os seguintes gráficos:
1. Histograma da variável total_bill
2. Scatterplot das variáveis tip e total_bill
3. Gráfico de barras da quantidade de refeições em cada dia da semana
4. Crie uma visualização que traga uma nova informação relevante além daquelas já vistas nos gráficos anteriores